-- MySQL Script generated by MySQL Workbench
-- 10/17/18 19:07:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema exercise5
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `exercise5` ;

-- -----------------------------------------------------
-- Schema exercise5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercise5` DEFAULT CHARACTER SET utf8 ;
USE `exercise5` ;

-- -----------------------------------------------------
-- Table `exercise5`.`note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercise5`.`note` ;

CREATE TABLE IF NOT EXISTS `exercise5`.`note` (
  `id` INT NOT NULL,
  `headline` VARCHAR(60) NULL,
  `content` VARCHAR(300) NULL,
  `create_date` DATE NULL,
  `change_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `headline_UNIQUE` ON `exercise5`.`note` (`headline` ASC);


-- -----------------------------------------------------
-- Table `exercise5`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercise5`.`tag` ;

CREATE TABLE IF NOT EXISTS `exercise5`.`tag` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise5`.`note_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercise5`.`note_tag` ;

CREATE TABLE IF NOT EXISTS `exercise5`.`note_tag` (
  `id` INT NOT NULL,
  `note_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_note_tag_note`
    FOREIGN KEY (`note_id`)
    REFERENCES `exercise5`.`note` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_note_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `exercise5`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_note_tag_note_idx` ON `exercise5`.`note_tag` (`note_id` ASC);

CREATE INDEX `fk_note_tag_tag1_idx` ON `exercise5`.`note_tag` (`tag_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
